modLoader="javafml" 
loaderVersion="[35,)"
issueTrackerURL="https://github.com/noobanidus/Lootr/issues"
license="https://github.com/noobanidus/Lootr/blob/1.15/LICENSE"
[[mods]] 
modId="lootr" 
version="${file.jarVersion}" 
displayName="Lootr" 
displayURL="https://minecraft.curseforge.com/projects/lootr" 
authors="Noobanidus"
description='''
Makes loot chest loot per-user.
'''
[[dependencies.Lootr]] 
    modId="forge" 
    mandatory=true 
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.Lootr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
